version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yashkundu
      POSTGRES_PASSWORD: yash123
      POSTGRES_DB: conferencedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
